export = AI;

declare global {
    export namespace AI {
        /**
         * This class represents an instance of the Dialogflow instance.
         */
        export interface DialogflowInstance {
            /**
             * Add a handler for specific event generated by the
             * specified Dialogflow instance. Use only functions as
             * handlers; anything except a function leads to the error
             * and scenario termination when a handler will be called.
             *
             * @param event The AI.DialogflowError,
             * AI.DialogflowQueryResult or
             * AI.DialogflowRecognitionResult event.
             * @param handler Handler function.
             */
            addEventListener(event: any, handler: (event: any) => void): void;

            /**
             * Add Dialogflow speech synthesis playback marker. The
             * {@link AI.Events.DialogflowPlaybackMarkerReached} event
             * will be triggered when the marker is reached.
             * Examples:
             * ```
             * instance.addMarker(1000);
             * ```
             *
             * ```
             * instance.addMarker(-2000);
             * ```
             *
             * @param offset Positive/negative offset (ms) from the
             * start/end of media.
             */
            addMarker(offset: number): void;

            /**
             * Remove the event handler for specific event generated by
             * the specified Dialogflow instance.
             *
             * @param event The AI.DialogflowError,
             * AI.DialogflowQueryResult or
             * AI.DialogflowRecognitionResult event.
             * @param handler Handler function.
             */
            removeEventListener(event: any, handler?: Function): void;

            /**
             * Send a query to the DialogFlow instance. You can send
             * either text string up to 256 characters or the event
             * object with the event name and the additional data.
             *
             * @param dialogflowQuery Text string (up to 256 characters)
             * or the event object.
             */
            sendQuery(dialogflowQuery: DialogflowQueryInput);

            /**
             * Update audio output parameter.
             *
             * @param outputAudioConfig
             */
            setOutputAudioConfig(outputAudioConfig: DialogflowOutputAudioConfig): void;

            /**
             * Set the collection of phrase hints for the intents.
             *
             * @param phraseHints The collection of phrase hints which
             * are used to boost accuracy of speech recognition.
             */
            setPhraseHints(phraseHints: object): void;

            /**
             * Set the parameters for the intents.
             *
             * @param queryParameters
             */
            setQueryParameters(queryParameters: DialogflowQueryParameters): void;

            /**
             * Stop and destroy current Dialogflow instance.
             */
            stop(): void;
        }
    }
}
